### ISSUE TITLE
Minimal demo

### ISSUE THREAD

**Issue by kafk3d** [QJPG/Humble-Plugin#1]
Hello! Thanks for the addon 👍 
It would be very helpful if you could provide a minimal working example with implementations of list of rooms, getting the list, refreshing the list and joining a room.
Unfortunately I was not successful in creating a working room's list, I got stuck somewhere on joining a created room, and getting the room's list required me to add additional functions to the net_manager and others core files, it feels now like I've taken a wrong turn.

**Comment by QJPG** [comment]
Hello, kafk3d!! I'm glad you enjoyed using the plugin. It's still under development, but it's stable enough to use. I'm currently working on the Match Maker features for it that will be added in the future. Seeing your open issue, I decided to send a small update that provides a list of the rooms created.
```gdscript
HumbleNetRemoteEventService.update_available_rooms()
	
var list_of_public_rooms = await HumbleNetRemoteEventService.available_room_list
```

I hope this helped you!!

**Comment by kafk3d** [comment]
Thanks, [QJPG](https://github.com/QJPG)! The update was really helpful. I'll be waiting for your matchmaker feature 🔥
